project_id = "cjgqtofxqhoubwnzyhlw"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-upgrade-email]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.offer-creation]
verify_jwt = false

[functions.funnel-builder]
verify_jwt = false

[functions.generate-copy]
verify_jwt = false

[functions.log-error]
verify_jwt = false

[functions.track-activity]
verify_jwt = false

[functions.log-session]
verify_jwt = false

[functions.end-session]
verify_jwt = false

[functions.manage-team]
verify_jwt = false

[functions.resolve-error]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.upsert-presence]
verify_jwt = false
